export const GET_BETTING_AMOUNT_OPTIONS = "GET_BETTING_AMOUNT_OPTIONS";
export const GET_SELECTED_BETTING_AMOUNT_OPTION =
  "GET_SELECTED_BETTING_AMOUNT_OPTION";
export const UPDATE_SELECTED_BETTING_AMOUNT_OPTION =
  "UPDATE_SELECTED_BETTING_AMOUNT_OPTION";
export const UPDATE_SELECTED_BETTING_OPTION = "UPDATE_SELECTED_BETTING_OPTION";
